spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mybank
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
    api-docs:
        path: /v3/api-docs

    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        org.springframework.security: DEBUG
        com.mybank: DEBUG